server:
  port: 8081
# Oracle Connect
spring:
  # Datasource Bean 생성
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: admin
    password: ahrilove1213
    
  #Jpa Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging.level:
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL 
  
# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml 

#upload Folder
com.al.blogAPI.images.path: images
com.al.blogAPI.upload.path: upload